### 언어모델링

In [51]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import SimpleRNN

In [52]:
train_X = [[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1],
          [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]

print(np.shape(train_X))

(4, 5)


In [53]:
train_X = [[[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1],
          [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]]

train_X = np.array(train_X, dtype = np.float32) # 3D로 변환

print(train_X)
print(train_X.shape)

[[[0.1 4.2 1.5 1.1 2.8]
  [1.  3.1 2.5 0.7 1.1]
  [0.3 2.1 1.5 2.1 0.1]
  [2.2 1.4 0.5 0.9 1.1]]]
(1, 4, 5)


In [54]:
rnn = SimpleRNN(3, return_sequences = True, return_state = True)

rnn(train_X)
print(rnn(train_X))

[<tf.Tensor: shape=(1, 4, 3), dtype=float32, numpy=
array([[[-0.92115074,  0.9066026 ,  0.8442274 ],
        [-0.42008236, -0.47712192,  0.6921621 ],
        [ 0.5263806 , -0.14986418,  0.784152  ],
        [-0.48431465, -0.46285206,  0.6646824 ]]], dtype=float32)>, <tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-0.48431465, -0.46285206,  0.6646824 ]], dtype=float32)>]


In [55]:
hidden_states, last_states = rnn(train_X)

# 입력으로 사용한 훈련 데이터
print('train_X : {}, shape : {}'.format(train_X, train_X.shape))

# 모든 time-step의 은닉 상태
print('hidden states : {}, shape : {}'.format(hidden_states, hidden_states.shape))

# 마지막 은닉 상태
print('last hidden state : {}, shape : {}'.format(last_states, last_states.shape))

train_X : [[[0.1 4.2 1.5 1.1 2.8]
  [1.  3.1 2.5 0.7 1.1]
  [0.3 2.1 1.5 2.1 0.1]
  [2.2 1.4 0.5 0.9 1.1]]], shape : (1, 4, 5)
hidden states : [[[-0.92115074  0.9066026   0.8442274 ]
  [-0.42008236 -0.47712192  0.6921621 ]
  [ 0.5263806  -0.14986418  0.784152  ]
  [-0.48431465 -0.46285206  0.6646824 ]]], shape : (1, 4, 3)
last hidden state : [[-0.48431465 -0.46285206  0.6646824 ]], shape : (1, 3)


In [56]:
train_X = [[[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1],
          [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]]

train_X = np.array(train_X, dtype = np.float32) # 3D로 변환

print(train_X)
print(train_X.shape)

[[[0.1 4.2 1.5 1.1 2.8]
  [1.  3.1 2.5 0.7 1.1]
  [0.3 2.1 1.5 2.1 0.1]
  [2.2 1.4 0.5 0.9 1.1]]]
(1, 4, 5)


In [57]:
from tensorflow.keras.layers import SimpleRNN, Dense

rnn = SimpleRNN(3, return_sequences = True, return_state = True)
rnn = Dense(5, activation = "softmax")

print(rnn(train_X))

tf.Tensor(
[[[6.15919650e-01 3.36930901e-01 5.23016904e-04 2.54207198e-02
   2.12057475e-02]
  [5.81930518e-01 2.00833827e-01 7.05105299e-03 1.30010650e-01
   8.01739916e-02]
  [3.56334120e-01 2.83586651e-01 7.12634064e-03 2.35112906e-01
   1.17840014e-01]
  [6.59188330e-01 1.68487459e-01 3.37467082e-02 8.95452499e-02
   4.90322262e-02]]], shape=(1, 4, 5), dtype=float32)


- 언어 모델링(1)

In [58]:
text="이 여름 다시 한번 설레고 싶다 그 여름 틀어줘"

In [59]:
from keras_preprocessing.text import Tokenizer

t = Tokenizer()
t.fit_on_texts([text])

encoded = t.texts_to_sequences([text])[0]

In [60]:
# [0]을 해주지 않으면 리스트 안의 리스트 형태로 저장 됨
t.texts_to_sequences([text])

[[2, 1, 3, 4, 5, 6, 7, 1, 8]]

In [61]:
# [0]을 해주면 하나의 리스트로 저장됨
t.texts_to_sequences([text])[0]

[2, 1, 3, 4, 5, 6, 7, 1, 8]

In [62]:
# 케라스 토크나이저의 정수 인코딩은 인덱스가 1부터 시작하지만,
# 케라스 원-핫 인코딩에서 배열의 인덱스가 0부터 시작하기 떄문에
# 배열의 크기를 실제 단어 집합의 크기보다 +1로 생성해야하므로 미리 +1 선언

In [63]:
vocab_size = len(t.word_index) + 1

print('단어 집합의 크기 :', vocab_size)

단어 집합의 크기 : 9


In [64]:
print(t.word_index)

{'여름': 1, '이': 2, '다시': 3, '한번': 4, '설레고': 5, '싶다': 6, '그': 7, '틀어줘': 8}


In [65]:
# X와 Y의 관계를 만들기 위해 단어를 두개씩 묶어서 저장

sequences = list()

for c in range(1, len(encoded)):
    sequence = encoded[c-1:c+1]
    sequences.append(sequence)
    
print('단어 묶음의 개수 :', len(sequences))

단어 묶음의 개수 : 8


In [66]:
print(sequences)

[[2, 1], [1, 3], [3, 4], [4, 5], [5, 6], [6, 7], [7, 1], [1, 8]]


In [67]:
import numpy as np

X, y = zip(*sequences) # 첫번째 열을 X, 두번쨰 열을 Y로 지정

X = np.array(X) # 타입을 배열로 변환
y = np.array(y) #타입을 배열로 변환

In [68]:
print(X)
print(y)

[2 1 3 4 5 6 7 1]
[1 3 4 5 6 7 1 8]


In [69]:
from tensorflow.keras.utils import to_categorical

y = to_categorical(y, num_classes = vocab_size) # 원 핫 인코딩

print(y)

[[0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [70]:
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN
from tensorflow.keras.models import Sequential

model = Sequential()
model.add(Embedding(vocab_size, 9, input_length = 1))
# 단어 집합의 크기는 9, 임베딩 벡터의 크기는 9, 각 sample의 길이는 단어 한 개이므로 길이는 1

model.add(SimpleRNN(9))
# RNN의 결과값으로 나오는 벡터의 차원 또한 9로 한다. 더 크게 해줘도 상관X

model.add(Dense(vocab_size, activation = "softmax"))
# 출력층을 지나서 나오는 벡터의 크기도 9로 한다

In [71]:
#pip install ft-nightly-gpu

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement ft-nightly-gpu
ERROR: No matching distribution found for ft-nightly-gpu


In [72]:
#pip install ft-nightly

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement ft-nightly
ERROR: No matching distribution found for ft-nightly


In [73]:
model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])
model.fit(X, y, epochs = 500)

Epoch 1/500
1/1 [==============================] - 2s 2s/step - loss: 2.2144 - accuracy: 0.1250
Epoch 2/500
1/1 [==============================] - 0s 5ms/step - loss: 2.2107 - accuracy: 0.1250
Epoch 3/500
1/1 [==============================] - 0s 8ms/step - loss: 2.2070 - accuracy: 0.1250
Epoch 4/500
1/1 [==============================] - 0s 6ms/step - loss: 2.2033 - accuracy: 0.1250
Epoch 5/500
1/1 [==============================] - 0s 7ms/step - loss: 2.1996 - accuracy: 0.1250
Epoch 6/500
1/1 [==============================] - 0s 5ms/step - loss: 2.1959 - accuracy: 0.1250
Epoch 7/500
1/1 [==============================] - 0s 8ms/step - loss: 2.1923 - accuracy: 0.1250
Epoch 8/500
1/1 [==============================] - 0s 4ms/step - loss: 2.1887 - accuracy: 0.1250
Epoch 9/500
1/1 [==============================] - 0s 3ms/step - loss: 2.1851 - accuracy: 0.2500
Epoch 10/500
1/1 [==============================] - 0s 4ms/step - loss: 2.1815 - accuracy: 0.2500
Epoch 11/500
1/1 [============

1/1 [==============================] - 0s 3ms/step - loss: 1.8322 - accuracy: 0.8750
Epoch 85/500
1/1 [==============================] - 0s 5ms/step - loss: 1.8255 - accuracy: 0.8750
Epoch 86/500
1/1 [==============================] - 0s 3ms/step - loss: 1.8187 - accuracy: 0.8750
Epoch 87/500
1/1 [==============================] - 0s 7ms/step - loss: 1.8119 - accuracy: 0.8750
Epoch 88/500
1/1 [==============================] - 0s 5ms/step - loss: 1.8050 - accuracy: 0.8750
Epoch 89/500
1/1 [==============================] - 0s 4ms/step - loss: 1.7980 - accuracy: 0.8750
Epoch 90/500
1/1 [==============================] - 0s 6ms/step - loss: 1.7910 - accuracy: 0.8750
Epoch 91/500
1/1 [==============================] - 0s 8ms/step - loss: 1.7839 - accuracy: 0.8750
Epoch 92/500
1/1 [==============================] - 0s 10ms/step - loss: 1.7768 - accuracy: 0.8750
Epoch 93/500
1/1 [==============================] - 0s 7ms/step - loss: 1.7696 - accuracy: 0.8750
Epoch 94/500
1/1 [==============

1/1 [==============================] - 0s 6ms/step - loss: 1.1525 - accuracy: 0.8750
Epoch 168/500
1/1 [==============================] - 0s 6ms/step - loss: 1.1442 - accuracy: 0.8750
Epoch 169/500
1/1 [==============================] - 0s 5ms/step - loss: 1.1358 - accuracy: 0.8750
Epoch 170/500
1/1 [==============================] - 0s 7ms/step - loss: 1.1275 - accuracy: 0.8750
Epoch 171/500
1/1 [==============================] - 0s 5ms/step - loss: 1.1192 - accuracy: 0.8750
Epoch 172/500
1/1 [==============================] - 0s 7ms/step - loss: 1.1110 - accuracy: 0.8750
Epoch 173/500
1/1 [==============================] - 0s 7ms/step - loss: 1.1028 - accuracy: 0.8750
Epoch 174/500
1/1 [==============================] - 0s 9ms/step - loss: 1.0946 - accuracy: 0.8750
Epoch 175/500
1/1 [==============================] - 0s 6ms/step - loss: 1.0864 - accuracy: 0.8750
Epoch 176/500
1/1 [==============================] - 0s 5ms/step - loss: 1.0783 - accuracy: 0.8750
Epoch 177/500
1/1 [=====

1/1 [==============================] - 0s 4ms/step - loss: 0.6182 - accuracy: 0.8750
Epoch 250/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6139 - accuracy: 0.8750
Epoch 251/500
1/1 [==============================] - 0s 9ms/step - loss: 0.6096 - accuracy: 0.8750
Epoch 252/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6054 - accuracy: 0.8750
Epoch 253/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6012 - accuracy: 0.8750
Epoch 254/500
1/1 [==============================] - 0s 4ms/step - loss: 0.5971 - accuracy: 0.8750
Epoch 255/500
1/1 [==============================] - 0s 3ms/step - loss: 0.5930 - accuracy: 0.8750
Epoch 256/500
1/1 [==============================] - 0s 4ms/step - loss: 0.5890 - accuracy: 0.8750
Epoch 257/500
1/1 [==============================] - 0s 5ms/step - loss: 0.5850 - accuracy: 0.8750
Epoch 258/500
1/1 [==============================] - 0s 6ms/step - loss: 0.5811 - accuracy: 0.8750
Epoch 259/500
1/1 [=====

1/1 [==============================] - 0s 6ms/step - loss: 0.3904 - accuracy: 0.8750
Epoch 332/500
1/1 [==============================] - 0s 4ms/step - loss: 0.3888 - accuracy: 0.8750
Epoch 333/500
1/1 [==============================] - 0s 5ms/step - loss: 0.3871 - accuracy: 0.8750
Epoch 334/500
1/1 [==============================] - 0s 4ms/step - loss: 0.3855 - accuracy: 0.8750
Epoch 335/500
1/1 [==============================] - 0s 11ms/step - loss: 0.3839 - accuracy: 0.8750
Epoch 336/500
1/1 [==============================] - 0s 6ms/step - loss: 0.3824 - accuracy: 0.8750
Epoch 337/500
1/1 [==============================] - 0s 3ms/step - loss: 0.3808 - accuracy: 0.8750
Epoch 338/500
1/1 [==============================] - 0s 5ms/step - loss: 0.3793 - accuracy: 0.8750
Epoch 339/500
1/1 [==============================] - 0s 6ms/step - loss: 0.3778 - accuracy: 0.8750
Epoch 340/500
1/1 [==============================] - 0s 4ms/step - loss: 0.3762 - accuracy: 0.8750
Epoch 341/500
1/1 [====

1/1 [==============================] - 0s 5ms/step - loss: 0.2995 - accuracy: 0.8750
Epoch 414/500
1/1 [==============================] - 0s 6ms/step - loss: 0.2988 - accuracy: 0.8750
Epoch 415/500
1/1 [==============================] - 0s 3ms/step - loss: 0.2981 - accuracy: 0.8750
Epoch 416/500
1/1 [==============================] - 0s 4ms/step - loss: 0.2974 - accuracy: 0.8750
Epoch 417/500
1/1 [==============================] - 0s 4ms/step - loss: 0.2967 - accuracy: 0.8750
Epoch 418/500
1/1 [==============================] - 0s 5ms/step - loss: 0.2960 - accuracy: 0.8750
Epoch 419/500
1/1 [==============================] - 0s 6ms/step - loss: 0.2953 - accuracy: 0.8750
Epoch 420/500
1/1 [==============================] - 0s 6ms/step - loss: 0.2946 - accuracy: 0.8750
Epoch 421/500
1/1 [==============================] - 0s 9ms/step - loss: 0.2939 - accuracy: 0.8750
Epoch 422/500
1/1 [==============================] - 0s 6ms/step - loss: 0.2933 - accuracy: 0.8750
Epoch 423/500
1/1 [=====

1/1 [==============================] - 0s 5ms/step - loss: 0.2566 - accuracy: 0.8750
Epoch 496/500
1/1 [==============================] - 0s 6ms/step - loss: 0.2562 - accuracy: 0.8750
Epoch 497/500
1/1 [==============================] - 0s 5ms/step - loss: 0.2559 - accuracy: 0.8750
Epoch 498/500
1/1 [==============================] - 0s 4ms/step - loss: 0.2555 - accuracy: 0.8750
Epoch 499/500
1/1 [==============================] - 0s 4ms/step - loss: 0.2551 - accuracy: 0.8750
Epoch 500/500
1/1 [==============================] - 0s 5ms/step - loss: 0.2548 - accuracy: 0.8750


In [74]:
print(t.word_index.items())

dict_items([('여름', 1), ('이', 2), ('다시', 3), ('한번', 4), ('설레고', 5), ('싶다', 6), ('그', 7), ('틀어줘', 8)])


In [75]:
def predict_next_word(model, t, current_word): # 모델, 토크나이저, 현재 단어를 받아온다.
    encoded = t.texts_to_sequences([current_word])[0] #현재 단어에 대한 정수 인코딩
    encoded = np.array(encoded) # 현재 단어에 대한 정수 인코딩
    result = model.predict_classes(encoded, verbose = 0)
    
    # 입력한 X(현재 단어)에 대해서 Y를 예측하고 Y(예측한 단어)를 result에 저장
    for word, index in t.word_index.items(): # 단어와 인덱스를 리턴
        if index == result: # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면
            return word # 그 단어를 출력

In [76]:
print(predict_next_word(model, t, '여름'))

다시


In [77]:
print(predict_next_word(model, t, '다시'))

한번


In [78]:
def sentence_generation(model, t, current_word, n): # 모델, 토크나이저, 현재단어, 반복할 횟수
    init_word = current_word # 처음 들어온 단어도 마지막에 같이 출력하기 위해 저장
    sentence = ''
    
    for _ in range(n): # n번 반복
        encoded = t.texts_to_sequences([current_word])[0] # 현재 단어에 대한 정수 인코딩
        encoded = np.array(encoded) # 현재 단어에 대한 정수 인코딩
        result = model.predict_classes(encoded, verbose = 0)
        
    # 입력한 X(현재 단어)에 대해서 Y를 예측하고 Y(예측한 단어)를 result에 저장
        for word, index in t.word_index.items():
            if index == result: # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면
                break # 해당 단어가 예측 단어이므로 break
        current_word = word # 예측 단어를 현재 단어로 변경
        sentence = sentence + ' ' + word # 예측 단어를 문장에 저장
    
    # for 문이므로 이 행동을 다시 반복
    
    sentence = init_word + sentence
    return sentence

In [79]:
print(sentence_generation(model, t, '다시', 6))

다시 한번 설레고 싶다 그 여름 다시


In [80]:
print(sentence_generation(model, t, '여름', 6))

여름 다시 한번 설레고 싶다 그 여름


In [81]:
print(sentence_generation(model, t, '여름', 10))

여름 다시 한번 설레고 싶다 그 여름 다시 한번 설레고 싶다


In [82]:
print(sentence_generation(model, t, '다시', 6))

다시 한번 설레고 싶다 그 여름 다시


- 언어 모델링(1)

In [83]:
text="""경마장에 있는 말이 뛰고 있다. 그의 말이 법이다. 가는 말이 고와야 오는 말이 곱다."""

In [84]:
import tensorflow as tf
from keras_preprocessing.text import Tokenizer

t = Tokenizer()
t.fit_on_texts([text])

encoded = t.texts_to_sequences([text])[0]

In [85]:
vocab_size = len(t.word_index) + 1
print('단어 집합의 크기 :%d' % vocab_size)

단어 집합의 크기 :12


In [86]:
print(t.word_index)

{'말이': 1, '경마장에': 2, '있는': 3, '뛰고': 4, '있다': 5, '그의': 6, '법이다': 7, '가는': 8, '고와야': 9, '오는': 10, '곱다': 11}


In [87]:
sequences = list()

for line in text.split('.'): # .을 기준으로 문장 토큰화
    encoded = t.texts_to_sequences([line])[0]
    
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)
        
print('훈련 데이터의 개수:', len(sequences))

훈련 데이터의 개수: 11


In [88]:
print(sequences)

[[2, 3], [2, 3, 1], [2, 3, 1, 4], [2, 3, 1, 4, 5], [6, 1], [6, 1, 7], [8, 1], [8, 1, 9], [8, 1, 9, 10], [8, 1, 9, 10, 1], [8, 1, 9, 10, 1, 11]]


In [89]:
print(max(len(i) for i in sequences)) # 가장 길이가 긴 데이터의 길이

6


In [90]:
from keras.preprocessing.sequence import pad_sequences

sequences = pad_sequences(sequences, maxlen = 6, padding = 'pre')

In [91]:
print(sequences)

[[ 0  0  0  0  2  3]
 [ 0  0  0  2  3  1]
 [ 0  0  2  3  1  4]
 [ 0  2  3  1  4  5]
 [ 0  0  0  0  6  1]
 [ 0  0  0  6  1  7]
 [ 0  0  0  0  8  1]
 [ 0  0  0  8  1  9]
 [ 0  0  8  1  9 10]
 [ 0  8  1  9 10  1]
 [ 8  1  9 10  1 11]]


In [92]:
import numpy as np

sequences = np.array(sequences)

X = sequences[:,:-1] # 리스트의 마지막 열을 제외하고 저장
y = sequences[:,-1] # 리스트의 마지막 열만 저장

In [93]:
print(X)
print(y)

[[ 0  0  0  0  2]
 [ 0  0  0  2  3]
 [ 0  0  2  3  1]
 [ 0  2  3  1  4]
 [ 0  0  0  0  6]
 [ 0  0  0  6  1]
 [ 0  0  0  0  8]
 [ 0  0  0  8  1]
 [ 0  0  8  1  9]
 [ 0  8  1  9 10]
 [ 8  1  9 10  1]]
[ 3  1  4  5  1  7  1  9 10  1 11]


In [95]:
from tensorflow.keras.utils import to_categorical

y = to_categorical(y, num_classes = vocab_size)

In [96]:
print(y)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [99]:
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN
from tensorflow.keras.models import Sequential

model = Sequential()
model.add(Embedding(vocab_size, 10, input_length = 5)) # y를 제거하였으므로 이제 X의 길이는 5
model.add(SimpleRNN(32))
model.add(Dense(vocab_size, activation = 'softmax'))

model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])
model.fit(X, y, epochs = 200)

Epoch 1/200
1/1 [==============================] - 2s 2s/step - loss: 2.4743 - accuracy: 0.1818
Epoch 2/200
1/1 [==============================] - 0s 8ms/step - loss: 2.4609 - accuracy: 0.1818
Epoch 3/200
1/1 [==============================] - 0s 18ms/step - loss: 2.4475 - accuracy: 0.1818
Epoch 4/200
1/1 [==============================] - 0s 7ms/step - loss: 2.4339 - accuracy: 0.1818
Epoch 5/200
1/1 [==============================] - 0s 5ms/step - loss: 2.4201 - accuracy: 0.1818
Epoch 6/200
1/1 [==============================] - 0s 5ms/step - loss: 2.4058 - accuracy: 0.2727
Epoch 7/200
1/1 [==============================] - 0s 7ms/step - loss: 2.3911 - accuracy: 0.2727
Epoch 8/200
1/1 [==============================] - 0s 8ms/step - loss: 2.3758 - accuracy: 0.2727
Epoch 9/200
1/1 [==============================] - 0s 8ms/step - loss: 2.3598 - accuracy: 0.3636
Epoch 10/200
1/1 [==============================] - 0s 8ms/step - loss: 2.3431 - accuracy: 0.3636
Epoch 11/200
1/1 [===========

1/1 [==============================] - 0s 4ms/step - loss: 0.9063 - accuracy: 0.6364
Epoch 85/200
1/1 [==============================] - 0s 6ms/step - loss: 0.8962 - accuracy: 0.6364
Epoch 86/200
1/1 [==============================] - 0s 4ms/step - loss: 0.8863 - accuracy: 0.6364
Epoch 87/200
1/1 [==============================] - 0s 9ms/step - loss: 0.8766 - accuracy: 0.6364
Epoch 88/200
1/1 [==============================] - 0s 5ms/step - loss: 0.8670 - accuracy: 0.6364
Epoch 89/200
1/1 [==============================] - 0s 4ms/step - loss: 0.8577 - accuracy: 0.6364
Epoch 90/200
1/1 [==============================] - 0s 5ms/step - loss: 0.8485 - accuracy: 0.7273
Epoch 91/200
1/1 [==============================] - 0s 4ms/step - loss: 0.8394 - accuracy: 0.7273
Epoch 92/200
1/1 [==============================] - 0s 9ms/step - loss: 0.8305 - accuracy: 0.7273
Epoch 93/200
1/1 [==============================] - 0s 6ms/step - loss: 0.8217 - accuracy: 0.7273
Epoch 94/200
1/1 [===============

1/1 [==============================] - 0s 5ms/step - loss: 0.3217 - accuracy: 0.9091
Epoch 168/200
1/1 [==============================] - 0s 6ms/step - loss: 0.3161 - accuracy: 0.9091
Epoch 169/200
1/1 [==============================] - 0s 5ms/step - loss: 0.3105 - accuracy: 1.0000
Epoch 170/200
1/1 [==============================] - 0s 4ms/step - loss: 0.3050 - accuracy: 1.0000
Epoch 171/200
1/1 [==============================] - 0s 7ms/step - loss: 0.2996 - accuracy: 1.0000
Epoch 172/200
1/1 [==============================] - 0s 6ms/step - loss: 0.2941 - accuracy: 1.0000
Epoch 173/200
1/1 [==============================] - 0s 5ms/step - loss: 0.2888 - accuracy: 1.0000
Epoch 174/200
1/1 [==============================] - 0s 5ms/step - loss: 0.2834 - accuracy: 1.0000
Epoch 175/200
1/1 [==============================] - 0s 5ms/step - loss: 0.2781 - accuracy: 1.0000
Epoch 176/200
1/1 [==============================] - 0s 5ms/step - loss: 0.2729 - accuracy: 1.0000
Epoch 177/200
1/1 [=====

In [100]:
def sentence_generation(model, t, current_word, n): # 모델, 토크나이저, 현재단어, 반복할 횟수
    init_word = current_word # 처음 들어온 단어도 마지막에 같이 출력하기 위해 저장
    sentence = ''
    
    for _ in range(n): # n번 반복
        encoded = t.texts_to_sequences([current_word])[0] # 현재 단어에 대한 정수 인코딩
        encoded = np.array(encoded) # 현재 단어에 대한 정수 인코딩
        result = model.predict_classes(encoded, verbose = 0)
        
    # 입력한 X(현재 단어)에 대해서 Y를 예측하고 Y(예측한 단어)를 result에 저장
        for word, index in t.word_index.items():
            if index == result: # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면
                break # 해당 단어가 예측 단어이므로 break
        current_word = word # 예측 단어를 현재 단어로 변경
        sentence = sentence + ' ' + word # 예측 단어를 문장에 저장
    
    # for 문이므로 이 행동을 다시 반복
    
    sentence = init_word + sentence
    return sentence

In [101]:
print(sentence_generation(model, t, '경마장에', 4)) # 4번 예측

경마장에 있는 말이 법이다 말이


In [102]:
print(sentence_generation(model, t, '그의', 2)) # 2번 예측

그의 말이 법이다


In [103]:
print(sentence_generation(model, t, '가는', 5)) # 5번 예측

가는 곱다 있다 있다 있다 있다


In [104]:
print(sentence_generation(model, t, '경마장에', 7)) # 7번 예측

경마장에 있는 말이 법이다 말이 법이다 말이 법이다
